### ISSUE TITLE
Help with my own project?

### ISSUE THREAD

**Issue by rsewell97** [dbdexter-dev/meteor_demod#1]
Hey, great library btw! 

I'm trying to make my own one of these in python. C isn't really my strong suit so would you be able to give a brief rundown of the sequence of operations which occur? From what I understand, you need to multiply the signal by sin(2*pi*f_c*t) and cos(2*pi*f_c*t), lowpass filter it (at some value) and you get a constellation from the two points?

Am I on the right track? Thanks!

**Comment by dbdexter-dev** [comment]
Hi, thanks for checking out my project!

Quick disclaimer: I'm by no means an expert at DSP, so take everything I say with a grain of salt.
With that said, there are four major blocks to implement in order to get the 4 points on the constellation diagram: AGC, signal filtering, symbol timing recovery, and carrier recovery.

So once you have an IQ recording of the QPSK signal, the first thing you should do is normalize its amplitude to a reasonable value. Otherwise you might have too strong of a signal on the input and clip it, or too weak of a signal and the upcoming stages won't pick it up. This is what the AGC is for (see agc.c).

Once you've done that, you'll want to filter your signal. This is to reduce ISI and improve the SNR. Since the satellite is applying a root-raised cosine filter, you'll want to apply the same root-raised cosine filter as well. The two together make a raised-cosine filter, which minimises ISI (see [here](https://www.michael-joost.de/rrcfilter.pdf) to get an idea of how this filter is implemented). To aid with symbol timing recovery, I'm interpolating the IQ stream right before passing it through the RRC filter (see interpolator.c:77).

Next up is symbol timing recovery. This is necessary because you only know the spacing between symbols (the symbol rate is a constant 72kbaud), but not when to sample the signal to get the best SNR (see demod.c:162). There are [a few algorithms](https://www.nutaq.com/blog/symbol-timing-recovery-methods-digital-iq-demodulator) to resolve this, I'm using the early-late algorithm since it's simple to implement and gives good enough results.

The final step is carrier recovery. Now you have a signal sampled at the right time to get the best SNR, and in order to demodulate it, you need to mix it with a local oscillator with the same frequency and phase as the transmitter. To achieve this, I'm implementing a [Costas loop](https://www.nutaq.com/blog/digital-iq-demodulator-carrier-recovery-using-costas-loops). A regular PLL won't do because the phase of the signal is constantly changing (that's what's carrying the data stream). So what a Costas loop does is compensate for the phase change due to the symbols being transmitted, and lock the local oscillator's phase and frequency to match the received signal's frequency and phase (see pll.c:46).

Plotting the output of the Costas loop on the I/Q plane will reveal the four constellation points typical of a QPSK signal, so all I'm doing at this stage is converting the complex samples into two 8-bit values, and writing those to the output file.

A higher-level view of the decoding process is inside demod\_thr\_run (see demod.c:123), where most of these steps are concatenated. Hopefully this is clear enough!

**Comment by rsewell97** [comment]
Very thorough explanation. I can see what to do now, thanks!
